server:
  port: 8081

spring:
  application:
    name: eventor-front

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나의 최대 크기
      max-request-size: 10MB # 요청 전체 크기 (여러 파일 포함 가능)

  # HTML form 에서 GET, POST 뿐 아니라 PUT, DELETE 도 사용하기 위해서 설정
  mvc:
    hidden method:
      filter:
        enabled: true

  jpa:
    open-in-view: false

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR