spring:
  # 재시작 및 라이브 리로드 활성화
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # 캐시 비활성화
  thymeleaf:
    cache: false

  data:
    redis:
      host: localhost
      password: wkddngurqudtls!

logging:
  file:
    path: ./logs

feignClient:
  url: localhost:8090