name: MiniMoment Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clean with Maven
        run: mvn clean

      - name: Install with Maven
        run: mvn install

      #      - name: Log in to Docker Hub
      #        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #
      #      - name: Build the Docker image
      #        run: docker build -t ${{ secrets.DOCKER_REPO }} .
      #
      #      - name: Push the Docker image
      #        run: docker push ${{ secrets.DOCKER_REPO }}

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # DockerHub Push
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/eventor .
          docker push ${{ secrets.DOCKER_USERNAME }}/eventor  

  deploy-ec2-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd eventor-front
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi dlrudgjs104/eventor:latest
            sudo docker-compose up -d